version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the React code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  base-directory: dist
  files:
    - '*'
    - '**/*'